[2022-09-05  15:04:21.388] base.py -> post_method line:39 [INFO] : case_id:1 - 登录测试
[2022-09-05  15:04:21.492] base.py -> post_method line:47 [INFO] : 请求体-->{"account": "18988889999", "accountType": 1, "cerificationType": 2}
[2022-09-05  15:04:21.493] base.py -> post_method line:48 [INFO] : 响应体-->{'code': 200, 'success': 1, 'message': '操作成功', 'data': {'smsCode': '7749'}, 'time': 1662361461480, 'traceId': '889455ba-9a29-495e-89ac-176ef8414a32'}
[2022-09-05  15:04:21.519] base.py -> equal line:115 [ERROR] : 操作成功 != None ->断言失败--FAIL
